//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNLPRJ.VisualStudio.PodcastWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpisodeContent
    {
        public int episodeNumber { get; set; }
        public string paragraphOne { get; set; }
        public string paragraphTwo { get; set; }
        public string paragraphThree { get; set; }
        public string paragraphFour { get; set; }
    }
}
